// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snyixoylsfkfsgcvxzbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueWl4b3lsc2ZrZnNnY3Z4emJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTg2NDcsImV4cCI6MjA2NDMzNDY0N30.rzoX4jMCPvhgEnMgkPSS4uB-8RtYBAkIWUaZQvWi2yE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);